m4_include([autoconf/ac_path_generic.m4])
m4_include([autoconf/encap.m4])
m4_include([autoconf/aclocal.m4])
m4_include([/usr/share/aclocal/ltoptions.m4])
m4_include([/usr/share/aclocal/lt~obsolete.m4])
m4_include([/usr/share/aclocal/libtool.m4])
m4_include([/usr/share/aclocal/ltversion.m4])
m4_include([/usr/share/aclocal/ltsugar.m4])
